包在组件ErrorBoundary中的代码如果出错,页面不会整个报错,其余部分还是可以正常显示

其实跟try catch很像  在组件内部 有任何逻辑错误 都会被catch捕获到
